enum CuisineEnum {
  afghan('Afghan', 'Afgan'),
  african('African', 'Afrika'),
  algerian('Algerian', 'Cezayir'),
  american('American', 'Amerikan'),
  amish('Amish', 'Amish'),
  argentine('Argentine', 'Arjantin'),
  armenian('Armenian', 'Ermeni'),
  asian('Asian', 'Asya'),
  asianInspired('Asian Inspired', 'Asya esintili'),
  australian('Australian', 'Avustralya'),
  austrian('Austrian', 'Avusturya'),
  authentic('Authentic', 'Otantik'),
  bangladeshi('Bangladeshi', 'Bangladeş'),
  belgian('Belgian', 'Belçika'),
  brazilian('Brazilian', 'Brezilya'),
  british('British', 'Britanya'),
  cajun('Cajun', 'Kajun'),
  canadian('Canadian', 'Kanada'),
  caribbean('Caribbean', 'Karayip'),
  chilean('Chilean', 'Şili'),
  chinese('Chinese', 'Çin'),
  chineseInspired('Chinese Inspired', 'Çin esintili'),
  colombian('Colombian', 'Kolombiya'),
  copycat('Copycat', 'Taklit'),
  creole('Creole', 'Kreol'),
  cuban('Cuban', 'Küba'),
  czech('Czech', 'Çek'),
  danish('Danish', 'Danimarka'),
  dutch('Dutch', 'Hollanda'),
  eastAfrican('East African', 'Doğu Afrika'),
  eastAndSoutheastAsian('East And Southeast Asian', 'Doğu ve Güneydoğu Asya'),
  easternEuropean('Eastern European', 'Doğu Avrupa'),
  egyptian('Egyptian', 'Mısır'),
  english('English', 'İngiliz'),
  ethiopian('Ethiopian', 'Etiyopya'),
  european('European', 'Avrupa'),
  filipino('Filipino', 'Filipin'),
  finnish('Finnish', 'Finlandiya'),
  french('French', 'Fransız'),
  frenchCanadian('French Canadian', 'Fransız-Kanada'),
  frenchInspired('French Inspired', 'Fransız esintili'),
  fusion('Fusion', 'Füzyon'),
  german('German', 'Alman'),
  greek('Greek', 'Yunan'),
  greekInspired('Greek Inspired', 'Yunan esintili'),
  hawaiian('Hawaiian', 'Hawaii'),
  hungarian('Hungarian', 'Macar'),
  indian('Indian', 'Hint'),
  indianInspired('Indian Inspired', 'Hint esintili'),
  indonesian('Indonesian', 'Endonezya'),
  inspired('Inspired', 'Esintili'),
  irish('Irish', 'İrlanda'),
  israeli('Israeli', 'İsrail'),
  italian('Italian', 'İtalyan'),
  italianInspired('Italian Inspired', 'İtalyan esintili'),
  jamaican('Jamaican', 'Jamaika'),
  japanese('Japanese', 'Japon'),
  japaneseInspired('Japanese Inspired', 'Japon esintili'),
  jewish('Jewish', 'Yahudi'),
  korean('Korean', 'Kore'),
  koreanInspired('Korean Inspired', 'Kore esintili'),
  kosher('Kosher', 'Koşer'),
  latin('Latin', 'Latin'),
  latinAmerican('Latin American', 'Latin Amerika'),
  lebanese('Lebanese', 'Lübnan'),
  malaysian('Malaysian', 'Malezya'),
  mediterraneanInspired('Mediterranean Inspired', 'Akdeniz esintili'),
  mexican('Mexican', 'Meksika'),
  mexicanInspired('Mexican Inspired', 'Meksika esintili'),
  middleEastern('Middle Eastern', 'Orta Doğu'),
  middleEasternInspired('Middle Eastern Inspired', 'Orta Doğu esintili'),
  moroccan('Moroccan', 'Fas'),
  nativeAmerican('Native American', 'Yerli Amerikan'),
  newEngland('New England', 'Yeni İngiltere'),
  newZealand('New Zealand', 'Yeni Zelanda'),
  northAfrican('North African', 'Kuzey Afrika'),
  northAmerican('North American', 'Kuzey Amerika'),
  norwegian('Norwegian', 'Norveç'),
  oceanic('Oceanic', 'Okyanusya'),
  pakistani('Pakistani', 'Pakistan'),
  pennsylvaniaDutch('Pennsylvania Dutch', 'Pensilvanya Hollandalısı'),
  persian('Persian', 'İran'),
  peruvian('Peruvian', 'Peru'),
  polish('Polish', 'Polonya'),
  portuguese('Portuguese', 'Portekiz'),
  puertoRican('Puerto Rican', 'Porto Riko'),
  russian('Russian', 'Rus'),
  salvadoran('Salvadoran', 'El Salvador'),
  scandinavian('Scandinavian', 'İskandinav'),
  scottish('Scottish', 'İskoç'),
  sichuan('Sichuan', 'Sıçuan'),
  sicilian('Sicilian', 'Sicilya'),
  southAfrican('South African', 'Güney Afrika'),
  southAmerican('South American', 'Güney Amerika'),
  southAndCentralAsian('South And Central Asian', 'Güney ve Orta Asya'),
  southern('Southern', 'Güney'),
  southwestern('Southwestern', 'Güneybatı'),
  spanish('Spanish', 'İspanyol'),
  sriLankan('Sri Lankan', 'Sri Lanka'),
  swedish('Swedish', 'İsveç'),
  swiss('Swiss', 'İsviçre'),
  syrian('Syrian', 'Suriye'),
  texMex('Tex Mex', 'Teks-Meks'),
  texMexHyphen('Tex-Mex', 'Teks-Meks'),
  thai('Thai', 'Tayland'),
  thaiInspired('Thai Inspired', 'Tayland esintili'),
  tunisian('Tunisian', 'Tunus'),
  turkish('Turkish', 'Türk'),
  us('U.S.', 'ABD'),
  ukAndIreland('Uk And Ireland', 'Birleşik Krallık ve İrlanda'),
  ukrainian('Ukrainian', 'Ukrayna'),
  venezuelan('Venezuelan', 'Venezuela'),
  vietnamese('Vietnamese', 'Vietnam'),
  welsh('Welsh', 'Galler'),
  westAfrican('West African', 'Batı Afrika'),
  world('World', 'Dünya');

  final String label;
  final String trLabel;
  const CuisineEnum(this.label, this.trLabel);

  static CuisineEnum? fromLabel(String? value) {
    if (value == null || value.trim().isEmpty) return null;
    final normalized = value.trim().toLowerCase();
    for (final cuisine in CuisineEnum.values) {
      if (cuisine.label.toLowerCase() == normalized) {
        return cuisine;
      }
    }
    return null;
  }
}
